language: node_js

node_js:
  - "node"
  - "lts/*"
  - "10"
  - "9"
  - "8"

script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/codeceptjs run && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  yarn: true
